# Generated by Django 5.2 on 2026-01-16 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите email адрес', max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(help_text='Введите полное имя', max_length=255, verbose_name='Полное имя получателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('comment', models.TextField(blank=True, help_text='Введите комментарий', verbose_name='Комментарий')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['full_name'],
                'permissions': [('can_view_all_recipients', 'Can view all recipients')],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Введите тему письма', max_length=255, verbose_name='Тема письма')),
                ('body', models.TextField(help_text='Введите тело письма', verbose_name='Тело письма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': 'Шаблон сообщения',
                'verbose_name_plural': 'Шаблоны сообщений',
                'ordering': ['-created_at'],
                'permissions': [('can_view_all_messages', 'Can view all messages')],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('in_progress', 'В процессе'), ('finished', 'Завершена')], default='created', max_length=20)),
                ('start_time', models.DateTimeField(help_text='Укажите дату и время начала рассылки', verbose_name='Время начала')),
                ('end_time', models.DateTimeField(help_text='Укажите дату и время окончания рассылки', verbose_name='Время окончания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
                ('clients', models.ManyToManyField(help_text='Выберите получателей рассылки', related_name='campaigns', to='campaigns.client', verbose_name='Клиенты')),
                ('message_template', models.ForeignKey(help_text='Выберите шаблон сообщения', on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.messagetemplate', verbose_name='Шаблон сообщения')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-created_at'],
                'permissions': [('can_view_all_campaigns', 'Can view all campaigns'), ('can_disable_campaign', 'Can disable campaign')],
            },
        ),
    ]
