# Generated by Django 5.2 on 2026-01-17 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='Ответ сервера SMTP')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Не успешно')], default='failed', max_length=20, verbose_name='Статус')),
                ('attempt_number', models.IntegerField(default=1)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='campaigns.campaign', verbose_name='Рассылка')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='campaigns.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
    ]
