# Generated by Django 5.2 on 2026-01-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_campaignattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Неактивные рассылки не могут быть отправлены", verbose_name="Активна"
            ),
        ),
    ]
